### ISSUE TITLE
Ways to ignore or support Plug.upload on request

### ISSUE THREAD

**Issue by iceniveth** [malomohq/accent#19]
There seems to be an issue with Plug.upload.

Following the guide on [file upload](https://www.phoenixframework.org/blog/file-uploads), shows error 
![image](https://user-images.githubusercontent.com/16744414/73805863-cf1adc80-4802-11ea-8028-3da278c1f30c.png)

This is whats on my `router.ex`
```ex
  pipeline :api do
    plug :accepts, ["json"]

    plug Plug.Parsers,
      parsers: [:urlencoded, :json],
      pass: ["*/*"],
      json_decoder: Jason

    plug Accent.Plug.Request # Removing this line will fix the issue
    
    plug Accent.Plug.Response,
      default_case: Accent.Case.Camel,
      header: "x-accent",
      supported_cases: %{"pascal" => Accent.Case.Pascal},
      json_codec: Jason
  end
```

**Comment by anthonator** [comment]
I'd expect placing `Plug.Upload` after `Accent.Plug.Request` would fix this issue. Are you able to do that?

**Comment by iceniveth** [comment]
I don't know how could I do that.

I just created another pipeline `:upload` which does not have `plug Accent.Plug.Request` and put my upload routes there.

**Comment by JustMikey** [comment]
> I'd expect placing `Plug.Upload` after `Accent.Plug.Request` would fix this issue. Are you able to do that?

Can you please elaborate on what you meant by that? And I wonder if there is a reason not to add a content-type check into the `Accept.Plug.Request` module?
