### ISSUE TITLE
snake case adding extra _

### ISSUE THREAD

**Issue by chungwong** [malomohq/accent#34]
There is an extra underscore added which is unexpected.
```elixir
iex(1)> Accent.Case.Snake.call("address2")      
"address_2"
iex(2)> Accent.Case.Snake.call("address_2")
"address__2"
```

I believe there should be a check around this line https://github.com/malomohq/accent/blob/master/lib/accent/case/snake.ex#L28

**Comment by anthonator** [comment]
Thanks for reporting.

This has been fixed in `v1.1.1`.
