### ISSUE TITLE
camelCase and PascalCase

### ISSUE THREAD

**Issue by iceniveth** [malomohq/accent#8]
Why is it that using `Accent.Transformer.PascalCase` converts the first letter of key to small and `Accent.Transformer.CamelCase` with capital? It should be the other way around I think.

**Comment by anthonator** [comment]
Yes, I’m aware. Thank you for creating an issue. I have plans to fix this in v2. I’ll keep this open until I have something for this released.

**Comment by anthonator** [comment]
I've fixed this in the [v1](https://github.com/malomohq/accent/tree/v1) branch. You can track progress there.

**Comment by anthonator** [comment]
Closed via #17
