### ISSUE TITLE
get_resp_header  in before_send_callback instead of get_req_header?

### ISSUE THREAD

**Issue by iceniveth** [malomohq/accent#9]
Just wondering, **responses.ex** on `before_send_callback`

https://github.com/sticksnleaves/accent/blob/9f5011677827d98e2cedf976f4120132b719004c/lib/accent/plugs/response.ex#L71

Should this be a
```elixir
get_req_header("content-type")
```

As on the `do_call?` uses `get_req_header("content-type")` on https://github.com/sticksnleaves/accent/blob/9f5011677827d98e2cedf976f4120132b719004c/lib/accent/plugs/response.ex#L99

I've tried to change it and all the tests are passing.

**Comment by iceniveth** [comment]
#10

**Comment by anthonator** [comment]
I believe the current implementation is correct. If the HTTP server decides to return a content type other than `application/json` then we don't want to case the response body.
